on:
  push:
    branches:
      - master
  release:
    types: [published]
  pull_request:
    branches:
      - master
jobs:

  buildNative:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        include:
          - os: ubuntu-latest
            scriptExt: "sh"
            libExt: "so"
            name: "linux"
          - os: windows-latest
            scriptExt: "bat"
            libExt: "dll"
            name: "windows"
    name: Build Natives - ${{ matrix.name }}
    runs-on:  ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v2
        with:
            fetch-depth: 1
            submodules: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
  
      - name: Install dependencies for linux
        if: matrix.name == 'linux'
        run: sudo apt update && sudo apt install libpulse-dev libglvnd-dev libx11-dev libopenal-dev libvulkan-dev libgl1-mesa-dev libgles2-mesa-dev libglu1-mesa-dev libgtk-3-dev ninja-build swig

      - name: Install dependencies for windows
        if: matrix.name == 'windows'
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install swig


      - name: Generate Swig Wrappers
        shell: bash
        run: |
          cd src
          chmod +x ./generate_swig_wrapper.${{ matrix.scriptExt }}
          ./generate_swig_wrapper.${{ matrix.scriptExt }}
          cd ..


      - name: Setup VSWhere.exe
        if: matrix.name == 'windows'
        uses: warrenbuckley/Setup-VSWhere@v1         

      - name: Build natives for ${{ matrix.name }}
        shell: bash
        run: |  
          if [ "${{ matrix.name }}" = "windows" ];
          then
              source .github/actions/tools/devenv.sh
          fi

          mkdir -p build/dist-native

          cd build
          
 
      
          cmake -DCMAKE_BUILD_TYPE=Release  -D USE_OPENGLES2=OFF -D USE_OPENGLES3=OFF -D USE_OPENGL3=ON -D BUILD_UNITYPLUGIN=OFF -D BUILD_METAL=OFF -D BUILD_DX12=OFF -D USE_OSM=OFF -D BUILD_VIEWER=OFF -D USE_DSOUND=OFF -D USE_XAUDIO2=OFF -D USE_OPENAL=OFF -D BUILD_EDITOR=OFF -D BUILD_VULKAN=OFF -D USE_MSVC_RUNTIME_LIBRARY_DLL=OFF -D BUILD_EXAMPLES=OFF ..
          cmake --build . --config Release

          dest="dist-native/${{ matrix.name }}/x86_64"
          mkdir -p "$dest"
          cp -v src/cpp/Release/*.${{ matrix.libExt }} "$dest"||cp -v src/cpp/*.${{ matrix.libExt }} "$dest"

      - name: Upload Build Dir
        uses: actions/upload-artifact@v1
        with:
          name: build-dir-${{ matrix.name }}
          path: build

      - name: Upload Natives
        uses: actions/upload-artifact@v1
        with:
          name: natives-${{ matrix.name }}
          path: build/dist-native

  buildJavaLibrary:
    needs: [buildNative]
    name: Build java library
    runs-on:  ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
            fetch-depth: 1
            submodules: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies for ubuntu-latest
        if: matrix.name == 'linux'
        run: sudo apt update && sudo apt install swig

      - name: Download Natives (linux)
        uses: actions/download-artifact@v1
        with:
          name: natives-linux
          path: build/dist-natives

      - name: Download Natives (windows)
        uses: actions/download-artifact@v1
        with:
          name: natives-windows
          path: build/dist-natives

      - name: Build Maven Artifacts
        shell: bash
        run: |
          cdd=$PWD
          cd build/dist-natives/
          for pl in *; do
              if [ -d "$pl" ]; then
                cd $pl
                for arch in *; do
                  if [ -d "$arch" ]; then
                    cd $arch
                    mkdir -p $cdd/build/java-natives/$pl/$arch/
                    cp -R *Java* $cdd/build/java-natives/$pl/$arch/
                    cd ..
                  fi
                done
                cd ..
              fi
          done
          cd "$cdd"
         

          export VERSION="`if [[ $GITHUB_REF == refs\/tags* ]]; then echo ${GITHUB_REF//refs\/tags\//}; fi`"
          if [ "$VERSION" = "" ];
          then
            branch="`if [[ $GITHUB_REF == refs\/heads* ]]; then echo ${GITHUB_REF//refs\/heads\//}; fi`"
            export VERSION="$branch-SNAPSHOT"
          fi

          cd src
          chmod +x ./generate_maven_artifacts.sh
          ./generate_maven_artifacts.sh
      
      - name: Upload Maven Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist-java
          path: build/maven


  buildCSharpLibrary:
    needs: [buildNative]
    name: Build C# library
    runs-on:  ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
            fetch-depth: 1
            submodules: true

      - name: Install dependencies for ubuntu-latest
        if: matrix.name == 'linux'
        run: sudo apt update && sudo apt install swig

      - name: Download Natives (linux)
        uses: actions/download-artifact@v1
        with:
          name: natives-linux
          path: build/dist-natives

      - name: Download Natives (windows)
        uses: actions/download-artifact@v1
        with:
          name: natives-windows
          path: build/dist-natives


      - name: Build C# Library
        shell: bash
        run: |
    

          cdd=$PWD
          cd build/dist-natives/
          for pl in *; do
              if [ -d "$pl" ]; then
                cd $pl
                for arch in *; do
                  if [ -d "$arch" ]; then
                    cd $arch
                    mkdir -p $cdd/build/dist-csharp/$pl/$arch/
                    cp -R *CSharp* $cdd/build/dist-csharp/$pl/$arch/
                    cd ..
                  fi
                done
                cd ..
              fi
          done
          cd "$cdd"
         

          cd src
          chmod +x ./generate_swig_wrapper.sh
          ./generate_swig_wrapper.sh
          cd ..

          mkdir -p build/dist-csharp/Effekseer
          cp -R src/csharp/swig build/dist-csharp/Effekseer/
      
      - name: Upload C# Library
        uses: actions/upload-artifact@v1
        with:
          name: dist-csharp
          path: build/dist-csharp

  buildPythonLibrary:
    needs: [buildNative]
    name: Build Python library
    runs-on:  ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
            fetch-depth: 1
            submodules: true

      - name: Install dependencies for ubuntu-latest
        if: matrix.name == 'linux'
        run: sudo apt update && sudo apt install swig

      - name: Download Natives (linux)
        uses: actions/download-artifact@v1
        with:
          name: natives-linux
          path: build/dist-natives

      - name: Download Natives (windows)
        uses: actions/download-artifact@v1
        with:
          name: natives-windows
          path: build/dist-natives


      - name: Build Python Library
        shell: bash
        run: |
    

          cdd=$PWD
          cd build/dist-natives/
          mkdir -p $cdd/build/dist-python/
          cp windows/x86_64/*Python.dll $cdd/build/dist-python/_EffekseerCore.pyd
          cp linux/x86_64/*Python.so $cdd/build/dist-python/_EffekseerCore.so

          cd "$cdd"
         
          cd src
          chmod +x ./generate_swig_wrapper.sh
          ./generate_swig_wrapper.sh
          cd ..

          cp -R src/python/swig/* build/dist-python/
      
      - name: Upload Python Library
        uses: actions/upload-artifact@v1
        with:
          name: dist-python
          path: build/dist-python



  deploy:
    needs: [buildCSharpLibrary,buildJavaLibrary,buildPythonLibrary]
    name: Deploy
    runs-on:  ubuntu-latest
    steps:
      - name: Download Maven Artifacts
        uses: actions/download-artifact@v1
        with:
          name: dist-java
          path: maven

      - name: Deploy Maven Artifacts to Package Registry
        if: github.event_name == 'release'
        run: |
          cd maven
          ls -lh
          set -e 
          files="`find . \( -name "*.jar" -o -name "*.pom" \) -type f -print`"
          set -f
          for art in $files; do
              file="${art:2}"
              dest="https://maven.pkg.github.com/$GITHUB_REPOSITORY/$file" 
              echo "Upload $file to $dest"
              curl -X PUT  $dest -H "Authorization: token  ${{ secrets.GITHUB_TOKEN }}" --upload-file $file -vvv
          done
          set +f

      - name: Deploy Maven Artifacts to Bintray
        if: github.event_name == 'release'
        run: |
          source .github/actions/tools/uploadToMaven.sh
          if [ "${{ secrets.BINTRAY_MAVEN_REPO }}" = "" ];
          then
            echo "Configure the following secrets to enable bintray deployment"
            echo "BINTRAY_MAVEN_REPO, BINTRAY_USER, BINTRAY_APIKEY"
          else
            uploadAllToMaven maven/ https://api.bintray.com/maven/${{ secrets.BINTRAY_MAVEN_REPO }} ${{ secrets.BINTRAY_USER }} ${{ secrets.BINTRAY_APIKEY }} "https://github.com/${GITHUB_REPOSITORY}" "${{ secrets.BINTRAY_LICENSE }}"
          fi
